name: PR
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
      - run: pnpm install
      - name: Update README
        run: pnpm update-posts
